---
- name: create vm from a template
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: create VM
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ vcenter_datacenter }}"
        #cluster: "{{ vcenter_cluster }}"
        name: "{{ vm_name }}"
        state: "{{ vm_state }}"
        folder: "ansible"
        template: "ansible_template"
        
    - name: Set the state of a virtual machine to poweroff
      vmware.vmware.vm_powerstate:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ vcenter_datacenter }}"
        validate_certs: false
        name: "{{ vm_name }}"
        state: powered-on
