---
- name: create vm from a template
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: create VM
      community.vmware.vmware_guest:
        hostname: "192.168.0.240"
        username: "administrator@vsphere.local"
        password: "Mildred!274"
        validate_certs: "false"
        datacenter: "Datacenter"
        name: "Test02"
        folder: "ansible"
        template: "ansible_template"
        state: "present"

    - name: Gather guest info
      vmware.vmware.guest_info:
        validate_certs: false
        hostname: "192.168.0.240"
        username: "administrator@vsphere.local"
        password: "Mildred!274"
        guest_name: "Test02"
