---
- name: Create a VM in VMware vCenter using VMware.vmware collection
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Clone VM from template
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
        datacenter: "{{ vcenter_datacenter }}"
        folder: ""
        name: "{{ vmname }}"
        template: "{{ vm_template }}"
        cluster: "{{ vcenter_cluster }}"
        datastore: "datastore1"
        state: poweredon
        hardware:
          memory_mb: "4096"
          num_cpus: "1"
        networks:
          - name: "VM Network"
            type: dynamic
        disk:
          - size_gb: "1"
            type: thin
            datastore: "datastore1"
      delegate_to: localhost
